"""Simulator-independent capabilities consumed by navigation methods.

Session state belongs to SuperNav. Native simulator objects and SDK value types
are deliberately absent from this surface; backend implementations translate
poses, paths, observations and ray hits at the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Protocol, Sequence


@dataclass(frozen=True)
class NavigationPath:
    geodesic_distance: float
    points: Sequence[Sequence[float]]


class NavigationPathfinder(Protocol):
    @property
    def is_loaded(self) -> bool: ...

    def shortest_path(self, start: Any, end: Any) -> NavigationPath | None: ...
    def snap_point(self, point: Any) -> Any: ...
    def get_topdown_view(self, meters_per_pixel: float, height: float) -> Any: ...
    def get_bounds(self) -> Any: ...
    def seed(self, seed: int) -> None: ...
    def get_random_navigable_point(self) -> Any: ...
    def is_navigable(self, point: Any) -> bool: ...


class RaycastScene(Protocol):
    def cast_ray(self, origin: Any, direction: Any, *, max_distance: float) -> Sequence[float]:
        """Return hit distances ordered from nearest to furthest."""
        ...


class NavigationSession(Protocol):
    """Owned application state; no native simulator or agent is exposed."""

    session_id: str
    mapless: bool
    step_count: int
    capture_counter: int
    scene_graph: Mapping[str, Any] | None
    last_visual_image_refs: dict[str, Any]
    latest_visual_capture_seq: int | None
    last_visible_nav_target_refs: set[str]
    last_visible_nav_targets: list[dict[str, Any]]
    last_panorama_images: list[dict[str, Any]]
    pending_visual_point_preview: dict[str, Any] | None
    pending_visual_ground_preview: dict[str, Any] | None


class NavigationBackend(Protocol):
    def navigation_session(self, session_id: str | None) -> NavigationSession: ...
    def navigation_pathfinder(self, session: NavigationSession) -> NavigationPathfinder: ...
    def navigation_scene(self, session: NavigationSession) -> RaycastScene: ...
    def agent_position(self, session: NavigationSession) -> Sequence[float]: ...
    def agent_rotation_wxyz(self, session: NavigationSession) -> Sequence[float]: ...
    def agent_forward(self, session: NavigationSession) -> Sequence[float]: ...
    def agent_heading_degrees(self, session: NavigationSession) -> float: ...
    def sensor_observations(self, session: NavigationSession) -> Mapping[str, Any]: ...
    def observations_at(self, session: NavigationSession, position: Any, rotation_xyzw: Any) -> Mapping[str, Any]: ...
    def navigate_step(self, session_id: str, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def step_action(self, session_id: str, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def get_panorama(self, session_id: str, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def step_and_capture(self, session_id: str, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def set_agent_state(self, session_id: str, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def publish_live_overlay(self, session: NavigationSession, overlay: Any, **metadata: Any) -> None: ...
    def session_output_dir(self, output_dir: str, session_id: str) -> str: ...
    def write_png_image(self, **kwargs: Any) -> dict[str, Any]: ...
    def to_rgb_topdown(self, raw_map: Any) -> Any: ...
    def draw_topdown_marker(self, *args: Any, **kwargs: Any) -> None: ...
    def draw_topdown_arrow(self, *args: Any, **kwargs: Any) -> None: ...
    def topdown_xy(self, pathfinder: NavigationPathfinder, point: Any, meters_per_pixel: float) -> tuple[int, int]: ...
